### ISSUE TITLE
Each Class Results on REAL275 and Wild6D

### ISSUE THREAD

**Issue by taeyeopl** [kywind/self-corr-pose#6]
Can you share the results of each class on the REAL275 and Wild6D (Related to Table 1 & Table 2 in the main paper)?

**Comment by kywind** [comment]
Hi taeyeopl, I am very sorry for the late response! 
Currently the checkpoints we provided on the Wild6D dataset were retrained, thus the numbers are different from the paper version, but they are a little higher so hope it is fine for you.
<img width="448" alt="image" src="https://github.com/kywind/self-corr-pose/assets/60169038/d2130aac-19b5-4aca-a525-c2928a1a51e2">

For the REAL275 part, due to resource limits I was not able to reorganize the code and get the checkpoints available for now, but I can share the paper version numbers. The upper and lower part corresponds to Ours-REAL and Ours-Wild6D in Table 2, respectively.
<img width="333" alt="image" src="https://github.com/kywind/self-corr-pose/assets/60169038/3b8d5f6d-369a-4fca-8966-8ec2291a4d89">

**Comment by kywind** [comment]
Hi taeyeopl, sorry for the late reply!

Table 1 (Wild6D):
<img width="520" alt="image" src="https://github.com/kywind/self-corr-pose/assets/60169038/e2252298-4d20-455e-82df-0c422d4a69b2">

Table 2 (REAL275, upper and lower part corresponds to Ours-REAL and Ours-Wild6D, respectively):
<img width="370" alt="image" src="https://github.com/kywind/self-corr-pose/assets/60169038/4326f5cf-da98-42ca-a8c4-62aea3a0013b">

**Comment by taeyeopl** [comment]
Thanks for sharing the results.
